# Site settings

baseurl: "" # the subpath of your site, e.g. /portfolio
url: "" # the base hostname & protocol for your site
language: "" # language to set into html tag, default is eng

# User settings
#
author: Leonardo Terceiro, B.Sc - ITIL - PSM
author-title: Information Technology Manager - IT Business Analyst
gravatar: 0260dd3a2bf1516033c4ee11c814c229
email: leonardo.terceiro@gmx.ca
linkedin: leonardoterceiro/en
github: leonardoterceiro
bio: "<ul>
<li>I am a qualified professional in the Health and Information Technology industry, as well as ITIL Foundation and Professional Scrum Master Certified. </li>
<li>Bachelor Degree in Information Systems Management, with over 10 years of leading people and being responsible for project and team management, having coached and mentored several direct reports and managing performance, expectations and results in different companies and enviroments.</li>
<li>I love to study and learn new skills and share knowledge and experiences with people around me. </li>
<li>Personally, I have the drive and determination to consistently achieve success as a leader in all of the organizations that I have worked with in the past. </li>
<li>I am proud of being able to deliver projects in a timely manner, under budget. </li>
<li>Proven ability to build rapport with clients and stakeholders with confidence and respect. </li>
<li>Strong analytical and problems solving skills.  </li>
<li>Well-developed organizational and time management skills, with the ability to balance multiple and competing priorities.</li>
<li>Demonstrated ability to pay persistent attention to detail, while maintaining an overall view of the strategic vision. </li>
<li>Excellent written and verbal communication skills. </li>
<li>Working toward PSPO and CAPM certifications.</li>
</ul>"

# Skills
#
# I'll use five differents levels:
# 1 - Studying: You know the basics of the skill and is studying it to get better
# 2 - Padawan: You know a little more than the basics and is comfortable to work with it
# 3 - Work with: You know how to handle the skill and how to properly use it in a real project
# 4 - Specialist: You have advanced knowledge of the skill and know how to use its best practices in a real project
# 5 - Jedi: You master the skill, know how and when to use and when not use it
#
# You can change these names in _includes/_skill-level-name.html if you wish
#
# If you don't want one of the sections below, leave the variable without any values

methodologies:
  - name: Agile Methodologies
    level: 4
  - name: Scrum Framework
    level: 4
  - name: RUP
    level: 4  
  - name: BABOK
    level: 4
  - name: PMBOK
    level: 4
  - name: PRINCE2
    level: 2
  - name: ITIL
    level: 4

front-end:
  - name: HTML 5
    level: 2
  - name: CSS 3
    level: 2
  - name: JavaScript
    level: 2
  - name: Angular
    level: 1
  - name: Bootstrap
    level: 1

back-end:
  - name: C#
    level: 3
  - name: Python
    level: 2
  - name: Java
    level: 2
  - name: SQL
    level: 3
  - name: PHP
    level: 2
  - name: Pearl
    level: 1
    
db:
  - name: MySQL
    level: 2
  - name: PostgreSQL
    level: 1
  - name: MongoDB
    level: 1
  - name: SQL Server
    level: 3
  - name: Oracle
    level: 1

devops:
  - name: Docker
    level: 1
  - name: Git
    level: 1
  - name: Continuous Integration
    level: 2
  - name: Continuous Delivery
    level: 2

others:
  - name: Web Services
    level: 2
  - name: Project Management
    level: 5
  - name: JEE, JSF, JPA, EJB, CDI
    level: 2
  - name: iReport, Jasper Reports
    level: 1
  - name: Business Analysis
    level: 5
  - name: UML
    level: 4
  - name: UX
    level: 4
  - name: OOD
    level: 3
  - name: SDLC
    level: 4
  - name: UAT
    level: 4
  - name: BPMN
    level: 3

# Build settings

markdown: kramdown
highlighter: rouge
sitemap: true # Generate sitemap.xml

sass:
  sass_dir: css
  style: compressed
## For more settings: https://jekyllrb.com/docs/configuration/

# exclude files if no need build
exclude: ['package.json', 'node_modules', 'README.md', 'LICENSE']

# Gems
gems: [jekyll-sitemap]
#
